server.port=8080

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/fincorp}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:fincorp}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:fincorp}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

services.simulator.base-url=${SIMULATOR_BASE_URL:http://localhost:8081}

spring.mail.host=${SPRING_MAIL_HOST:localhost}
spring.mail.port=${SPRING_MAIL_PORT:1025}
spring.mail.username=${SPRING_MAIL_USERNAME:}
spring.mail.password=${SPRING_MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=${SPRING_MAIL_AUTH:false}
spring.mail.properties.mail.smtp.starttls.enable=${SPRING_MAIL_STARTTLS:false}
notifications.email.sender=${NOTIFICATION_SENDER:no-reply@fincorp.local}
